export default class Auth {
    static SIGNUP = 'SIGNUP';
    static SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
    static SIGNUP_REJECTED = 'SIGNUP_REJECTED';

    static SIGNIN = 'SIGNIN';
    static SIGNIN_SUCCESSFUL = 'SIGNIN_SUCCESSFUL';
    static SIGNIN_REJECTED = 'SIGNIN_REJECTED';

    static LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
}